// ── Game Modes ──────────────────────────────────────────────────
// Moved from App.jsx to break circular dependencies.
// Components that need GAME_MODES, CATEGORIES, or recordRecentGame
// should import from this file instead of App.jsx.

export const GAME_MODES = [
  {
    id: "tic_tac_toe",
    path: "/tic-tac-toe",
    title: "Tic Tac Toe",
    badge: "Classic",
    category: "Casual Games",
    hero: "❌⭕",
    intro: "Classic 3x3 Tic Tac Toe.",
    rules: "Match 3 in a row to win.",
    reference: "Casual game.",
    accent: "#40e0f0",
    summary: "Tic Tac Toe",
    details: "Play against a friend or the computer.",
  },
  {
    id: "rock_paper_scissors",
    path: "/rock-paper-scissors",
    title: "Rock Paper Scissors",
    badge: "Classic",
    category: "Casual Games",
    hero: "✊✋✌️",
    intro: "Classic Rock Paper Scissors.",
    rules: "Rock beats Scissors, Scissors beats Paper, Paper beats Rock.",
    reference: "Casual game.",
    accent: "#f04060",
    summary: "Rock Paper Scissors",
    details: "Play against a friend or the computer.",
  },
  {
    id: "chess",
    path: "/chess",
    title: "Chess",
    badge: "Strategy",
    category: "Casual Games",
    hero: "♟️",
    intro: "Classic game of strategy.",
    rules: "Checkmate the opponent's king.",
    reference: "Standard rules.",
    accent: "#a855f7",
    summary: "Chess",
    details: "Play against a friend or the computer.",
  },
  {
    id: "stateCapital",
    path: "/state-capital",
    title: "State Capital Quiz",
    badge: "GK Memory",
    category: "General Knowledge",
    hero: "IND",
    intro: "Indian state capitals at exam speed.",
    rules: "<1s = 12pts · <2s = 8pts · <3s = 4pts · wrong = over",
    reference: "Covers the 28 Indian states only, not union territories.",
    accent: "#fb7185",
    summary: "Find the capital of the state. ",
    details: "A general knowledge memory test with a pink accent.",
  },
  {
    id: "nationalOfficials",
    path: "/national-officials",
    title: "National Officials",
    badge: "General Knowledge",
    category: "General Knowledge",
    hero: "GOV",
    intro: "Who currently holds this important national office?",
    rules: "<1s = 12pts · <2s = 8pts · <3s = 4pts · wrong = over",
    reference: "Current Indian constitutional and national officials.",
    accent: "#f59e0b",
    summary: "Who is the...",
    details: "Important office holders in India.",
  },
  {
    id: "stateOfficials",
    path: "/state-officials",
    title: "State Chief Ministers",
    badge: "General Knowledge",
    category: "General Knowledge",
    hero: "CM",
    intro: "Who is the current Chief Minister of this state?",
    rules: "<1s = 12pts · <2s = 8pts · <3s = 4pts · wrong = over",
    reference: "Current Chief Ministers of all 28 states.",
    accent: "#ef4444",
    summary: "Who is the Chief Minister of...",
    details: "Match the state to its current CM.",
  },
  {
    id: "diseaseCause",
    path: "/disease-cause",
    title: "Disease → Cause",
    badge: "Biology",
    category: "Biology",
    hero: "🦠",
    intro: "What causes this disease — virus, bacteria, fungus, or protozoa?",
    rules: "<1s = 12pts · <2s = 8pts · <3s = 4pts · wrong = over",
    reference: "50 important diseases and their causative organisms.",
    accent: "#10b981",
    summary: "What causes...",
    details: "Match diseases to their causative organisms.",
  },
  {
    id: "animalKingdom",
    path: "/animal-kingdom",
    title: "Animal Kingdom",
    badge: "Biology",
    category: "Biology",
    hero: "🐾",
    intro: "What class does this animal belong to?",
    rules: "<1s = 12pts · <2s = 8pts · <3s = 4pts · wrong = over",
    reference:
      "65 animals across 9 phyla — Chordata, Arthropoda, Mollusca, Echinodermata, Annelida, Cnidaria, Porifera, Platyhelminthes, Nematoda.",
    accent: "#22d3ee",
    summary: "What class is this animal?",
    details: "Match animals to their biological class.",
  },
  {
    id: "alphabet",
    path: "/alphabet",
    title: "Alphabet Quiz",
    badge: "Memory",
    category: "Memory & Logic",
    hero: "A→Z",
    intro: "Identify letter positions instantly.",
    rules: "<1s = 12pts · <2s = 8pts · <3s = 4pts · wrong = over",
    reference: "A·B·C·D·E·F·G·H·I·J·K·L·M·N·O·P·Q·R·S·T·U·V·W·X·Y·Z",
    accent: "#f0e040",
    summary: "What position is the letter?",
    details: "A fast recall drill built around alphabet position memory.",
  },
  {
    id: "square",
    path: "/square",
    title: "Square Quiz",
    badge: "Quant",
    category: "Mathematics",
    hero: "X²",
    intro: "Squares of numbers from 1 to 100.",
    rules: "<1.5s = 12pts · <3s = 8pts · <5s = 4pts · wrong = over",
    reference: "Practice squares of numbers from 1 to 100.",
    accent: "#40e0f0",
    summary: "What is the square of the number?",
    details: "A quick mental math mode with a cyan arcade accent.",
  },
  {
    id: "cube",
    path: "/cube",
    title: "Cube Quiz",
    badge: "Quant",
    category: "Mathematics",
    hero: "X³",
    intro: "Cubes of numbers from 1 to 30.",
    rules: "wrong = game over",
    reference: "Practice cubes of numbers from 1 to 30.",
    accent: "#a78bfa",
    summary: "What is the cube of the number?",
    details:
      "A challenging cube calculations mode with a purple arcade accent.",
  },
  {
    id: "worldCapital",
    path: "/world-capital",
    title: "World Capital Quiz",
    badge: "🌍 World GK",
    category: "General Knowledge",
    hero: "🌍",
    intro: "All 195 countries — test your world knowledge.",
    rules: "wrong = game over",
    reference: "All 195 countries — from Afghanistan to Zimbabwe.",
    accent: "#34d399",
    summary: "Name the capital of every country on Earth.",
    details: "A comprehensive world geography quiz with an emerald accent.",
  },
  {
    id: "periodicTable",
    path: "/periodic-table",
    title: "Element → (Atomic Number, Atomic Weight)",
    badge: "Chemistry",
    category: "Chemistry",
    hero: "Z|W",
    intro: "Match each element to its atomic number and atomic weight.",
    rules: "wrong = game over",
    reference: "Elements 1-118 with rounded atomic weights.",
    accent: "#f59e0b",
    summary: "Pick the correct atomic number and atomic weight.",
    details: "A chemistry recall drill — element to (Z, W) pairs.",
  },
  {
    id: "multiplication",
    path: "/multiplication",
    title: "Multiplication Quiz",
    badge: "Quant",
    category: "Mathematics",
    hero: "A×B",
    intro: "Times tables from 2 to 15 — speed counts.",
    rules: "<1s = 12pts · <2s = 8pts · <3s = 4pts · wrong = over",
    reference: "Products of two numbers between 2 and 15.",
    accent: "#22d3ee",
    summary: "What is the product?",
    details: "A fast times-table drill with a cyan accent.",
  },
  {
    id: "reverseAlphabet",
    path: "/reverse-alphabet",
    title: "Reverse Alphabet Quiz",
    badge: "Memory",
    category: "Memory & Logic",
    hero: "Z←A",
    intro: "Given a position, name the letter.",
    rules: "<1s = 12pts · <2s = 8pts · <3s = 4pts · wrong = over",
    reference: "A=1 · B=2 · … · Z=26",
    accent: "#e879f9",
    summary: "Which letter is at this position?",
    details: "The flip side of Alpha Quiz — position to letter recall.",
  },
  {
    id: "prime",
    path: "/prime",
    title: "Prime Number Quiz",
    badge: "Quant",
    category: "Mathematics",
    hero: "P#",
    intro: "Spot the prime among four numbers.",
    rules: "wrong = game over",
    reference: "Primes between 2 and 100.",
    accent: "#f97316",
    summary: "Pick the only prime number.",
    details: "A number theory challenge with an orange accent.",
  },
  {
    id: "roman",
    path: "/roman",
    title: "Roman Numerals Quiz",
    badge: "Classics",
    category: "Miscellaneous",
    hero: "IV",
    intro: "Convert Roman numerals to decimal values.",
    rules: "wrong = game over",
    reference: "Numbers 1–100 in standard Roman notation.",
    accent: "#84cc16",
    summary: "What is the value of the numeral?",
    details: "Decode numerals from I to C with a lime accent.",
  },
  {
    id: "countryCurrency",
    path: "/country-currency",
    title: "Country → Currency",
    badge: "🌍 World GK",
    category: "General Knowledge",
    hero: "💱",
    intro: "Match each country to its official currency.",
    rules: "wrong = game over",
    reference: "All 195 countries — from Afghanistan to Zimbabwe.",
    accent: "#2dd4bf",
    summary: "What currency does this country use?",
    details: "A world economics and geography quiz with a teal accent.",
  },
  {
    id: "elementSymbol",
    path: "/element-symbol",
    title: "Element Name → Element Symbol",
    badge: "Chemistry",
    category: "Chemistry",
    hero: "C·Fe",
    intro: "Match each element name to its chemical symbol.",
    rules: "wrong = game over",
    reference: "Elements 1-118 — from H to Og.",
    accent: "#eab308",
    summary: "What is the symbol for this element?",
    details: "Name to symbol recall — C, Fe, Au, and all 118 elements.",
  },
  {
    id: "oneWordSub",
    path: "/one-word-sub",
    title: "One Word Substitution",
    badge: "Vocabulary",
    category: "English",
    hero: "OWS",
    intro: "One word for the given phrase.",
    rules: "<1s = 12pts · <2s = 8pts · <3s = 4pts · wrong = over",
    reference: "100 common one-word substitutions.",
    accent: "#c084fc",
    summary: "Pick the one-word substitution for the phrase.",
    details: "A vocabulary quiz covering 100 common OWS entries.",
  },
  {
    id: "indianPresident",
    path: "/indian-president",
    title: "Indian Presidents",
    badge: "India GK",
    category: "General Knowledge",
    hero: "IND",
    intro: "Order → President name.",
    rules: "<1s = 12pts · <2s = 8pts · <3s = 4pts · wrong = over",
    reference: "1st to 15th President of India.",
    accent: "#f97316",
    summary: "Who was the Nth President of India?",
    details: "From Rajendra Prasad (1st) to Droupadi Murmu (15th).",
  },
  {
    id: "indianVicePresident",
    path: "/indian-vice-president",
    title: "Indian Vice Presidents",
    badge: "India GK",
    category: "General Knowledge",
    hero: "IVP",
    intro: "Order → Vice President name.",
    rules: "<1s = 12pts · <2s = 8pts · <3s = 4pts · wrong = over",
    reference: "1st to 14th Vice President of India.",
    accent: "#fb7185",
    summary: "Who was the Nth Vice President of India?",
    details: "From S. Radhakrishnan (1st) to Jagdeep Dhankhar (14th).",
  },
  {
    id: "siUnits",
    path: "/si-units",
    title: "SI Units Quiz",
    badge: "Physics",
    category: "Physics",
    hero: "SI",
    intro: "What is the SI unit for the given physical quantity?",
    rules: "<1s = 12pts · <2s = 8pts · <3s = 4pts · wrong = over",
    reference:
      "7 base units + 22 derived units — Newton, Pascal, Joule and more.",
    accent: "#818cf8",
    summary: "What is the SI unit of...",
    details: "Match physical quantities to their correct SI units.",
  },
  {
    id: "scientificName",
    path: "/scientific-name",
    title: "Scientific Names Quiz",
    badge: "Biology",
    category: "Biology",
    hero: "🧬",
    intro: "What is the scientific (binomial) name of this organism?",
    rules: "<1s = 12pts · <2s = 8pts · <3s = 4pts · wrong = over",
    reference:
      "60 organisms — mammals, birds, reptiles, insects, plants & microbes.",
    accent: "#34d399",
    summary: "Scientific name of...",
    details: "Match organisms to their Latin binomial names.",
  },
  {
    id: "stateDance",
    path: "/state-dance",
    title: "State & Dance Quiz",
    badge: "Culture",
    category: "General Knowledge",
    hero: "💃",
    intro: "Which state is famous for this folk or classical dance?",
    rules: "<1s = 12pts · <2s = 8pts · <3s = 4pts · wrong = over",
    reference: "Prominent Indian state dances like Kathak, Bihu, and Garba.",
    accent: "#fb7185",
    summary: "State of...",
    details: "Match Indian states to their famous dances.",
  },
  {
    id: "orgHq",
    path: "/organization-hq",
    title: "Organizations & HQ Quiz",
    badge: "GK Memory",
    category: "General Knowledge",
    hero: "🏢",
    intro: "Where is the headquarters of this organization?",
    rules: "<1s = 12pts · <2s = 8pts · <3s = 4pts · wrong = over",
    reference: "25 prominent global and Indian organizations.",
    accent: "#60a5fa",
    summary: "Headquarters of...",
    details: "Match international organizations to their headquarters.",
  },
  {
    id: "invention",
    path: "/inventions",
    title: "Inventions & Innovators Quiz",
    badge: "Science GK",
    category: "Science",
    hero: "💡",
    intro: "Who invented or discovered this?",
    rules: "<1s = 12pts · <2s = 8pts · <3s = 4pts · wrong = over",
    reference: "25 famous inventions and their creators.",
    accent: "#fbbf24",
    summary: "Inventor of...",
    details: "Match world-changing inventions to their creators.",
  },
  {
    id: "companyOrigin",
    path: "/company-origin",
    title: "Company Origins Quiz",
    badge: "Business GK",
    category: "General Knowledge",
    hero: "🏭",
    intro: "Which country is this famous company from?",
    rules: "<1s = 12pts · <2s = 8pts · <3s = 4pts · wrong = over",
    reference:
      "35+ companies across Tech, Vehicles, Food, Fashion, and Electronics.",
    accent: "#f43f5e",
    summary: "Origin of...",
    details: "Match famous global companies to their home countries.",
  },
  {
    id: "famousQuotes",
    path: "/famous-quotes",
    title: "Famous Quotes Quiz",
    badge: "History & GK",
    category: "General Knowledge",
    hero: "💬",
    intro: "Who said this famous quote?",
    rules: "<1s = 12pts · <2s = 8pts · <3s = 4pts · wrong = over",
    reference:
      "30 of the most iconic quotes from history, science, and politics.",
    accent: "#a78bfa",
    summary: "Who said...",
    details:
      "Match iconic historical quotes and slogans to the people who said them.",
  },
  {
    id: "riverOrigin",
    path: "/river-origin",
    title: "River → Origin",
    badge: "Geography",
    category: "General Knowledge",
    hero: "🌊",
    intro: "Where does this river originate?",
    rules: "<1s = 12pts · <2s = 8pts · <3s = 4pts · wrong = over",
    reference: "30 major Indian and world rivers and their sources.",
    accent: "#38bdf8",
    summary: "Origin of...",
    details: "Match rivers to where they begin.",
  },
  {
    id: "nationalPark",
    path: "/national-parks",
    title: "National Parks → State",
    badge: "India GK",
    category: "General Knowledge",
    hero: "🌲",
    intro: "Which Indian state is this national park in?",
    rules: "<1s = 12pts · <2s = 8pts · <3s = 4pts · wrong = over",
    reference: "30 famous Indian national parks and tiger reserves.",
    accent: "#4ade80",
    summary: "State of...",
    details: "Match Indian national parks to their states.",
  },
  {
    id: "landmarkCountry",
    path: "/landmark-country",
    title: "Landmark → Country",
    badge: "🌍 World GK",
    category: "General Knowledge",
    hero: "🗼",
    intro: "Which country is this famous landmark in?",
    rules: "<1s = 12pts · <2s = 8pts · <3s = 4pts · wrong = over",
    reference: "30 iconic landmarks from India and around the world.",
    accent: "#f472b6",
    summary: "Country of...",
    details: "Match famous landmarks to their countries.",
  },
  {
    id: "vitaminDeficiency",
    path: "/vitamin-deficiency",
    title: "Vitamin → Deficiency",
    badge: "Biology",
    category: "Biology",
    hero: "💊",
    intro: "What disease is caused by deficiency of this vitamin?",
    rules: "<1s = 12pts · <2s = 8pts · <3s = 4pts · wrong = over",
    reference: "13 vitamins and their deficiency diseases.",
    accent: "#fb923c",
    summary: "Deficiency of...",
    details: "Match vitamins to the diseases they prevent.",
  },
  {
    id: "indianNational",
    path: "/indian-national",
    title: "Indian National Symbols",
    badge: "India GK",
    category: "General Knowledge",
    hero: "🇮🇳",
    intro: "What is the official name of this Indian national symbol?",
    rules: "<1s = 12pts · <2s = 8pts · <3s = 4pts · wrong = over",
    reference:
      "20 official Indian national symbols — animal, bird, tree, sport, and more.",
    accent: "#f97316",
    summary: "Name of...",
    details: "Match national symbol categories to their official names.",
  },
  {
    id: "famousBattles",
    path: "/famous-battles",
    title: "Famous Battles → Year",
    badge: "History",
    category: "General Knowledge",
    hero: "⚔️",
    intro: "In which year was this famous battle fought?",
    rules: "<1s = 12pts · <2s = 8pts · <3s = 4pts · wrong = over",
    reference: "30 landmark battles from Indian and world history.",
    accent: "#dc2626",
    summary: "Year of...",
    details: "Match historic battles to the year they were fought.",
  },
  {
    id: "compoundFormula",
    path: "/compound-formula",
    title: "Compound → Formula",
    badge: "Chemistry",
    category: "Chemistry",
    hero: "H₂O",
    intro: "Match each compound name to its chemical formula.",
    rules: "<1s = 12pts · <2s = 8pts · <3s = 4pts · wrong = over",
    reference: "Common chemical compounds.",
    accent: "#ec4899",
    summary: "What is the formula for...",
    details: "Match compounds to their formulas.",
  },
  {
    id: "simon_says",
    path: "/simon-says",
    title: "Simon Says",
    badge: "Memory",
    category: "Mind Games",
    hero: "🧠",
    intro: "Watch the pattern. Repeat the pattern. How far can you go?",
    rules: "Each level adds a new color. Wrong tap = game over.",
    reference: "Classic memory sequence game.",
    accent: "#40e0f0",
    summary: "Simon Says",
    details: "Test your working memory with increasing sequences.",
  },
];

export const CATEGORIES = [
  { label: "All", icon: "🎯" },
  { label: "Mathematics", icon: "📐" },
  { label: "Physics", icon: "⚡" },
  { label: "Biology", icon: "🧬" },
  { label: "Chemistry", icon: "⚗️" },
  { label: "General Knowledge", icon: "📚" },
  { label: "Memory & Logic", icon: "🧠" },
  { label: "English", icon: "✍️" },
  { label: "Miscellaneous", icon: "🎲" },
  { label: "Mind Games", icon: "🧩" },
];

// ── Recently played helpers ──────────────────────────────────────────────────
const RECENT_KEY = "arcade_recent_games";
const RECENT_MAX = 4;

export function recordRecentGame(gameId) {
  try {
    const existing = JSON.parse(localStorage.getItem(RECENT_KEY) || "[]");
    const filtered = existing.filter((r) => r.id !== gameId);
    const updated = [{ id: gameId, playedAt: Date.now() }, ...filtered].slice(
      0,
      RECENT_MAX,
    );
    localStorage.setItem(RECENT_KEY, JSON.stringify(updated));
  } catch {
    /* ignore */
  }
}

export function getRecentGames() {
  try {
    return JSON.parse(localStorage.getItem(RECENT_KEY) || "[]");
  } catch {
    /* ignore */
    return [];
  }
}
